// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJyfzuuPycCWvFpYy_O4gk6SDFls9Q6I',
    appId: '1:661117108166:web:fe82f44745da84b634fcc7',
    messagingSenderId: '661117108166',
    projectId: 'bookstore-c8e54',
    authDomain: 'bookstore-c8e54.firebaseapp.com',
    storageBucket: 'bookstore-c8e54.appspot.com',
    measurementId: 'G-EJX5BEVTFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0LEGByV6XzUZBeD2C1dgtuntIMtdcxE',
    appId: '1:661117108166:android:435b642d4fb2ba1034fcc7',
    messagingSenderId: '661117108166',
    projectId: 'bookstore-c8e54',
    storageBucket: 'bookstore-c8e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCS3I2F_OT0w7lGDR995CdO-3UjGhqMk',
    appId: '1:661117108166:ios:108fe1fd99ee906234fcc7',
    messagingSenderId: '661117108166',
    projectId: 'bookstore-c8e54',
    storageBucket: 'bookstore-c8e54.appspot.com',
    iosBundleId: 'com.example.bookStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCS3I2F_OT0w7lGDR995CdO-3UjGhqMk',
    appId: '1:661117108166:ios:7108b156b401d33234fcc7',
    messagingSenderId: '661117108166',
    projectId: 'bookstore-c8e54',
    storageBucket: 'bookstore-c8e54.appspot.com',
    iosBundleId: 'com.example.bookStoreApp.RunnerTests',
  );
}
